// Mood data — genres, sort and filters per mood. lib/moodQuery.ts turns it into TMDB params.
// TMDB Genre IDs: 28=Action, 16=Animation, 35=Comedy, 18=Drama, 14=Fantasy,
// 36=History, 27=Horror, 10749=Romance, 878=Sci-Fi, 53=Thriller, 10751=Family,
// 9648=Mystery, 80=Crime, 10752=War
// Keyword IDs live in lib/tmdbKeywords.ts, by name.

import { TMDB_KEYWORDS } from "@/lib/tmdbKeywords";
import type { MoodConfig } from "@/lib/types";
export const moodMap: Record<string, MoodConfig> = {
  laugh: {
    key: "laugh",
    tagLabel: "Need to laugh",
    label: "Laugh until it hurts",
    description: "Comedy, feel-good, absurd",
    accentColor: "gold",
    genres: [35],
    excludeGenres: [27],
    sortBy: "popularity.desc",
    voteCountGte: 500,
    signatureFilm: { tmdbId: 346698, title: "Barbie", year: 2023, posterPath: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg" },
  },
  beautiful: {
    key: "beautiful",
    tagLabel: "Feel something beautiful",
    label: "Something beautiful",
    description: "Gorgeous drama, visual poetry",
    accentColor: "rose",
    genres: [18, 10749],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.0,
    signatureFilm: { tmdbId: 666277, title: "Past Lives", year: 2023, posterPath: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg" },
  },
  unsettled: {
    key: "unsettled",
    tagLabel: "Feel uneasy",
    label: "Slow-burn tension",
    description: "Gets under your skin",
    accentColor: "rose",
    genres: [53, 27, 9648],
    sortBy: "vote_average.desc",
    voteCountGte: 300,
    voteAverageGte: 6.5,
    signatureFilm: { tmdbId: 467244, title: "The Zone of Interest", year: 2023, posterPath: "/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg" },
  },
  thrilling: {
    key: "thrilling",
    tagLabel: "Need a rush",
    label: "Pure adrenaline",
    description: "Non-stop action, high octane",
    accentColor: "ember",
    genres: [28, 53],
    excludeGenres: [35],
    sortBy: "popularity.desc",
    voteCountGte: 400,
    signatureFilm: { tmdbId: 575264, title: "Mission: Impossible - Dead Reckoning Part One", year: 2023, posterPath: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg" },
  },
  thoughtful: {
    key: "thoughtful",
    tagLabel: "Mind needs feeding",
    label: "Layers on layers",
    description: "Changes how you see things",
    accentColor: "violet",
    genres: [878, 18],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.5,
    signatureFilm: { tmdbId: 693134, title: "Dune: Part Two", year: 2024, posterPath: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg" },
  },
  easy: {
    key: "easy",
    tagLabel: "Need a hug",
    label: "Warm & familiar",
    description: "Comforting, wholesome",
    accentColor: "teal",
    genres: [35, 10751, 16],
    sortBy: "popularity.desc",
    voteCountGte: 300,
    voteAverageGte: 7.0,
    keywords: [TMDB_KEYWORDS.friendship.id],
    signatureFilm: { tmdbId: 840430, title: "The Holdovers", year: 2023, posterPath: "/VHSzNBTwxV8vh7wylo7O9CLdac.jpg" },
  },
  cry: {
    key: "cry",
    tagLabel: "Need to let it out",
    label: "A good cry",
    description: "Emotional, cathartic",
    accentColor: "blue",
    genres: [18, 10749],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.0,
    signatureFilm: { tmdbId: 994108, title: "All of Us Strangers", year: 2023, posterPath: "/aviJMFZSnnCAsCVyJGaPNx4Ef3i.jpg" },
  },
  escape: {
    key: "escape",
    tagLabel: "Want to disappear",
    label: "Sweeping visuals await",
    description: "Films that transport you",
    accentColor: "blue",
    genres: [878, 14, 16],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.0,
    signatureFilm: { tmdbId: 792307, title: "Poor Things", year: 2023, posterPath: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg" },
  },
  family: {
    key: "family",
    tagLabel: "Everyone's watching",
    label: "Watch with family",
    description: "Fun for all ages",
    accentColor: "teal",
    genres: [10751, 16, 35],
    sortBy: "popularity.desc",
    voteCountGte: 300,
    signatureFilm: { tmdbId: 569094, title: "Spider-Man: Across the Spider-Verse", year: 2023, posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg" },
  },
  inspiring: {
    key: "inspiring",
    tagLabel: "Want to dream",
    label: "Something inspiring",
    description: "Stories that lift you up",
    accentColor: "gold",
    genres: [18, 36],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.5,
    signatureFilm: { tmdbId: 872585, title: "Oppenheimer", year: 2023, posterPath: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg" },
  },
  datenight: {
    key: "datenight",
    tagLabel: "Date night",
    label: "Easy-watch together",
    description: "Rom-com vibes, no heavy stuff",
    accentColor: "rose",
    genres: [35, 10749],
    excludeGenres: [27, 10752],
    sortBy: "popularity.desc",
    voteCountGte: 400,
    keywords: [TMDB_KEYWORDS.romanticComedy.id],
    signatureFilm: { tmdbId: 1072790, title: "Anyone But You", year: 2023, posterPath: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg" },
  },
  nostalgic: {
    key: "nostalgic",
    tagLabel: "Take me back",
    label: "Wistful & nostalgic",
    description: "Coming-of-age, tender memories",
    accentColor: "gold",
    genres: [18, 10749],
    sortBy: "vote_average.desc",
    voteCountGte: 200,
    voteAverageGte: 7.0,
    keywords: [TMDB_KEYWORDS.comingOfAge.id],
    signatureFilm: { tmdbId: 391713, title: "Lady Bird", year: 2017, posterPath: "/gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg" },
  },
  mindbending: {
    key: "mindbending",
    tagLabel: "Bend my mind",
    label: "Reality-shifting puzzles",
    description: "Twists, loops, what-is-real",
    accentColor: "violet",
    genres: [878, 53],
    sortBy: "vote_average.desc",
    voteCountGte: 300,
    voteAverageGte: 7.0,
    keywords: [TMDB_KEYWORDS.mindBending.id, TMDB_KEYWORDS.dystopia.id],
    signatureFilm: { tmdbId: 545611, title: "Everything Everywhere All at Once", year: 2022, posterPath: "/u68AjlvlutfEIcpmbYpKcdi09ut.jpg" },
  },
  dark: {
    key: "dark",
    tagLabel: "Go dark",
    label: "Cold, gritty, bleak",
    description: "Neo-noir, crime, moral grey",
    accentColor: "ember",
    genres: [80, 53, 18],
    sortBy: "vote_average.desc",
    voteCountGte: 300,
    voteAverageGte: 6.8,
    keywords: [TMDB_KEYWORDS.neoNoir.id],
    signatureFilm: { tmdbId: 800158, title: "The Killer", year: 2023, posterPath: "/ipkcgvN7h3yZnbYowthloHLKsf4.jpg" },
  },
  weird: {
    key: "weird",
    tagLabel: "Something weird",
    label: "Off-kilter & surreal",
    description: "Cult-leaning, quirky, strange",
    accentColor: "teal",
    genres: [35, 18, 14],
    sortBy: "vote_average.desc",
    voteCountGte: 150,
    voteAverageGte: 6.8,
    // No keyword: "cult film" tags too few films to carry a mood on its own.
    signatureFilm: { tmdbId: 798286, title: "Beau Is Afraid", year: 2023, posterPath: "/wgVkkjigF31r1nZV80uV0xNIoun.jpg" },
  },
};

// All moods as an array for UI iteration
export const allMoods = Object.values(moodMap);
